### ISSUE TITLE
Auto scaling for spring boot service container

### ISSUE THREAD

**Issue by vishvarodrigo** [sahajsoft/docker-swarm-service-autoscaler#5]
Configurations are exactly same as yours, what i did is replaced the web container image in to my own container image in compose file. port also the same (8080). It always shows "Nan" as a metric value. when i put your web docker image, it works fine and metric shows properly.﻿

Compose File : 
```
version: "3.4"

services:
  web:
    image: localhost:5000/test-service1
    ports:
      - "8080:8080"
  fintech-test-service2:
    image: localhost:5000/test-service2
    ports:
      - "8081:8080"

  prometheus:
    image: quay.io/prometheus/prometheus:v2.0.0
    ports:
      - "9090:9090"
    command: "--config.file=/etc/prometheus/prometheus.yml"
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml

  autoscaler:
    image: sahajsoft/docker-swarm-service-autoscaler:latest
    command: "/etc/docker-swarm-service-autoscaler/autoscaler.yml --log-leve=DEBUG"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: autoscaler.yml
        target: /etc/docker-swarm-service-autoscaler/autoscaler.yml
    deploy:
      placement:
        constraints:
          - node.role == manager

configs:
  prometheus.yml:
    file: ./prometheus.yml
  autoscaler.yml:
    file: ./autoscaler.yml
```

**Comment by endeepak** [comment]
If you are using same `prometheus.yml`, please check if the your service exposes metrics in prometheus format on either http://<service-ip>:8080 or http://<service-ip>:8080 

If you have custom config for `prometheus.yml` and `autoscaler.yml`, please share it for further debugging

**Comment by vishvarodrigo** [comment]
I;m using same 

> prometheus.yml

 and spring boot service sending metrics to prometheus through port 

> 9090

.

**Comment by endeepak** [comment]
If your service exposes metrics on `9090`, you should update `prometheus.yml` to reflect that

```
- job_name: 'web'
    dns_sd_configs:
    - names:
      - 'tasks.web'
      type: 'A'
      port: 9090
```

**Comment by vishvarodrigo** [comment]
Got the issue. My service not exposed port to outside. What i did is connected containers by its name in the compose file. But promethous.yml trying to access container using host and port. that is not allowed. Can i connect to the container using its name or is it necessary to access via host and port (prometheus.yml)?

**Comment by endeepak** [comment]
You should be able to use the service name like

```
- job_name: 'fintech-test-service2'
    dns_sd_configs:
    - names:
      - 'tasks.fintech-test-service2'
      type: 'A'
      port: 9090
```
