### ISSUE TITLE
How to create multiple autoscaler service?

### ISSUE THREAD

**Issue by yuswitayudi** [sahajsoft/docker-swarm-service-autoscaler#8]
I've tried adding a service, and adding it to the autoscaler.yml config. but when I try to benchmark on the new service that I added not on the prometheus metric there is no grow up cpu usage. But when benchmarking the example_web application on port 8080, the application that I installed the cpu usage also went up.

This my example autoscaler.yml

```
poll_interval_seconds: 10
metric_stores:
  - name: monitoring
    type: prometheus
    prometheus:
      url: http://example_prometheus:9090
  - name: monitoring-backend
    type: prometheus
    prometheus:
      url: http://example_prometheus:9090
autoscale_rules:
  - service_name: example_web
    scale_min: 1
    scale_max: 3
    scale_step: 1
    metric_store: monitoring
    metric_query: scalar(avg(rate(http_requests_total{job="web"}[30s])))
    scale_up_threshold: 10
    scale_down_threshold: 5
  - service_name: netbrand-backend_netbrand-backend
    scale_min: 1
    scale_max: 3
    scale_step: 1
    metric_store: monitoring-backend
    metric_query: scalar(avg(rate(http_requests_total{job="web"}[30s])))
    scale_up_threshold: 90
    scale_down_threshold: 60
```

Thanks for your advice
